---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
         username: ${{secrets.DOCKERHUB_USER}}
         password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        env:
          SECRET_KEY: j8)__g76b!#55^#6t#26)mu2wc8q-j*!(qjxdzs$=el#^9+c_5
        run: docker-compose run --rm app sh -c 'python manage.py test'
      - name: Lint
        run: docker-compose run --rm app sh -c 'flake8'

